### ISSUE TITLE
Server backup costs off by factor of 100

### ISSUE THREAD

**Issue by hziegeldorf** [jangraefen/hcloud-pricing-exporter#1]
**Describe the bug**

I think that the monthly costs (haven't checked the daily ones) for server backups are off by a factor of 100.

**To Reproduce**
1. Create servers with backups enabled.
2. Check server prices and server backup prices.

**Screenshot**
![image](https://user-images.githubusercontent.com/7589858/119944690-de441180-bf94-11eb-962f-faa58469dc4f.png)

I calculated the right backup costs. They're exactly `23.228` which is what's displayed divided by `100`.

**Expected behavior**
That server backup prices are ~10% of the server prices.

**Additional context**
I think the error is the following:

- [Here](https://github.com/jangraefen/hcloud-pricing-exporter/blob/main/fetcher/prices.go#L47) you get a percentage from the Hetzner API, i.e., `10`.
- [Then](https://github.com/jangraefen/hcloud-pricing-exporter/blob/main/fetcher/server_backups.go#L55) you multiply with the server prices without adjusting the percentage, i.e., without dividing by 100.

**Comment by jangraefen** [comment]
Hello @hziegeldorf,

Thank you very much for letting me know.
I will take a look next week and am optimistic that the fix is fairly trivial. If you want, you can take a swing at a fix as well if you want to have it fixed before next week 😄.

With kind regards

**Comment by jangraefen** [comment]
Hey @hziegeldorf,

Thank you again for the report. I have release a version containing the fixed backup calculation. You can get it as `v0.3.1` from DockerHub or as `0.3.1-r2` from the Helm repository.

With kind regards
