### ISSUE TITLE
Helm installation instructions don't work

### ISSUE THREAD

**Issue by kscarlett** [jangraefen/hcloud-pricing-exporter#12]
I'm not sure if this is something common, as I don't have a lot of experience using Helm, but upon trying to install following the given instructions, I get the following:

`Error: INSTALLATION FAILED: file '/Users/kscarlett/Library/Caches/helm/repository/hcloud-pricing-exporter' does not appear to be a gzipped archive; got 'text/html; charset=utf-8'`

This might be related to how the chart it is deployed? I have been able to install Traefik and a couple of other applications through Helm.

**Comment by jangraefen** [comment]
Hey,

sorry to hear that you are experiencing troubles installing the Helm chart. Could you maybe elaborate what steps you performed that lead to the error?

With kind regards,
Jan

**Comment by kscarlett** [comment]
I followed the instructions in the readme, as below:

```
helm repo add hcloud-pricing-exporter https://jangraefen.github.io/hcloud-pricing-exporter
helm repo update
helm upgrade --install hcloud-pricing-exporter hcloud-pricing-exporter/hcloud-pricing-exporter
```

I also did a regular `helm install` and tried with and without a couple of additional settings (for the API key), but none of those should or did have an impact.

When I curl the repo URL (or do `helm pull`), it returns the following:

```html
<html>
<head>
    <meta http-equiv="refresh" content="0; url=https://jangraefen.github.io/hcloud-pricing-exporter/index.yaml">
</head>
<p><a href="https://jangraefen.github.io/hcloud-pricing-exporter/index.yaml">Redirect to repo index.yaml</a></p>
</html>
```

I think this redirect is not correctly being followed.

For added context, I'm running helm v3.7.0.

**Comment by jangraefen** [comment]
Thanks for the clarifications. I am away for the weekend, but will have a look next week. Alternatively, if you feel like looking into it yourself, a PR or further analysis is more then welcome.

Sorry for the inconveniences.
