### ISSUE TITLE
Using deprecated field for traffic prices.

### ISSUE THREAD

**Issue by apricote** [jangraefen/hcloud-pricing-exporter#148]
**Describe the bug**

You are using a deprecated field from the API (`pricing.Traffic()`) for calculating traffic costs.

- https://github.com/jangraefen/hcloud-pricing-exporter/blob/b6b53a850d4b6dd54736395c57de13b7ef46fb39/fetcher/server_traffic.go#L44
- https://github.com/jangraefen/hcloud-pricing-exporter/blob/b6b53a850d4b6dd54736395c57de13b7ef46fb39/fetcher/loadbalancer_traffic.go#L44

These fields will be set to `0` on 2024-08-05. Please take a look at the [changelog](https://docs.hetzner.cloud/changelog#2024-07-25-cloud-api-returns-traffic-information-in-different-format) and the [hcloud-go v2.12.0 release notes](https://github.com/hetznercloud/hcloud-go/releases/tag/v2.12.0)

**Comment by jangraefen** [comment]
Thank you @apricote for letting me know and even linking the affected lines of code. That is what I call service 🙂.
I am building a new release as we speak.
