### ISSUE TITLE
Better grouping and summing of resources

### ISSUE THREAD

**Issue by danielr1996** [jangraefen/hcloud-pricing-exporter#159]
**Is your feature request related to a problem? Please describe.**

I'm tasked with creating a grafana dashboard that shows the total expenses as well as expenses grouped by different criteria (e.g. location), to better illustrate I'm using the following examples:

**Sum total expenses**
`sum({__name__=~"hcloud_pricing_server_monthly|hcloud_pricing_loadbalancer_monthly|..."})`

** Sum expenses by location**
`sum by (location) ({__name__=~"hcloud_pricing_server_monthly|hcloud_pricing_loadbalancer_monthly|..."})`

It works, but it's ugly because I have to specify each of the separate metrics in every query.

**Describe the solution you'd like**

While working with various prometheus exporters I recognized that instead of distinguishing a metrics by it's name they usually put the distinguishing criteria as a label, so the examples would become:

**Sum total expenses**
`sum(hcloud_pricing_resource_monthly)`

** Sum expenses by location**
`sum by (location) (hcloud_pricing_resource_monthly)`

Usually my rule of thumb is: If the sum of different metrics still makes sense, keep it as one metric and distinguish it by labels, if the somes makes no sense, keep the metrics separate, so the hourly and monthly metrics still make sense, because summing the hourly and monthly prices would make no sense.

For the implementation I have two suggestions:

**Suggestion 1: implement the changes in code**
This has the benefit of it being available to everyone using hcloud-pricing-exporter, no matter if it's run in kubernetes or on bare metal, but it might require a bit of effort.

**Suggestion 2: Provide custom recording rules with prometheus operator**
Since a ServiceMonitor is already included in the helm release (thanks for that ❤️) we could easily also include the recording rules, the recording rule for one metrics looks like this: 

```yaml
 - record: hcloud_pricing_resource_monthly
    expr: hcloud_pricing_server_monthly
    labels:
        resource: server
```
This is the workaround I'm currently using, but it requires the prometheus operator which is not an issue for me because I use it anyways, but it might for others. Also it might be confusing and hard to troubleshoot issues when the available metrics differ between deployment methods. 

If you like suggestion 2 I'd be happy to submit a PR.

**Additional context**
Here's a screenshot of my dashboard for those who are interested

![image](https://github.com/user-attachments/assets/0b75cd63-e1d7-47d1-a17a-5996124679b3)

**Comment by jangraefen** [comment]
Hey @danielr1996 ,

I will definitely look into your suggestion. Sadly I will be busy tomorrow, but I should find some time until the end of the week.

Right now, I think I prefer option one and will just offer additional metrics to also offer this feature to non Kubernetes users (like myself 😉).

Glad that to see that the exporter is of use to you 👍.

With kind regards,
Jan

**Comment by jangraefen** [comment]
Hey @danielr1996,

I just gave your suggestion some thought, but I can't quite work around the fact that some of the metrics have different labels already, so it is hard to align them all into a single metric.

- Loadbalancers, loadbalancer traffic, servers, server backups, server traffic, and floating IPs all have:
  - location
  - type
 - Primary IPs have:
   - datacenter
   - type
 - Volumes have:
   - bytes
   - location
 - Snapshots have no additional labels

How is your approach of merging them all together into a single metric? Right now I am tempted to conclude that this is actually not really fitting into the project but is more of a customization that is specific to your use-case. But I would be really interested in better understand your approach on the different labels.

With kind regards,
Jan
