### ISSUE TITLE
Error: failed to download "hcloud-pricing-exporter/hcloud-pricing-exporter"

### ISSUE THREAD

**Issue by jorikseldeslachts** [jangraefen/hcloud-pricing-exporter#44]
I can't seem to install this chart using the instructions. I always keep getting:

`Error: failed to download "hcloud-pricing-exporter/hcloud-pricing-exporter"`

**Comment by jangraefen** [comment]
Hello @jorikseldeslachts,

thanks for opening this issue. I just tried to replicate this issue, but it seems to work fine for me. What version are you using? I am using `v0.6.0-r1` while testing.

Could you share some additional information?
- Which command exactly is failing?
- Which machine are you running this command on? Does it have access to the internet?
- What is the output if you append `--debug` to the failing command?

With kind regards
Jan

**Comment by jangraefen** [comment]
Hello @jorikseldeslachts,

any news on this issue? Without any additional input, I will have to close it and just assume it is solved...

With kind regards
Jan
